services:
  java-demo:
    build:
      context: ./java-demo
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/mysql"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "passwd"
      OTEL_SERVICE_NAME: "demo-service"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://openobserve:5080/api/default"
      OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Basic cm9vdEBleGFtcGxlLmNvbTpMM0N3Y0xmc0xVS1hjZndi"

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "Complexpass#123"
    ports:
      - "5080:5080"
    volumes:
      - ./data:/data

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: "passwd"